language: c

compiler:
  - clang
  - gcc

os:
  - osx
  - linux

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9 # docopt uses <regex>, which requires 4.9+
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"

install: ./build-debug.sh

script: ./build/debug/test/all_tests
