language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9 # docopt uses <regex>, which requires 4.9+
            - doxygen
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9" DOCS="true"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - clang++-3.6
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
    - os: osx
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
    - os: osx
      env:
        - MATRIX_EVAL="" # default clang

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - ./build-debug.sh
  - ./build-release.sh

script:
  - ./build/debug/test/all_tests
  - ./build/release/test/all_tests

after_success: |   
    if [ "$DOCS" = "true" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      doxygen ./Doxyfile
    fi 

deploy: 
  provider: pages
  local-dir: "./docs/html/"
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true # keeps commit history of gh-pages branch
  on:
     branch: master
     condition: $DOCS = true
