#include "ion_internal.h"

// This is generated by cmake using git and available tags.
#include "build_version.h"

char const *ion_version(void) {
   return IONC_VERSION;
}

char const *ion_version_full(void) {
   return IONC_BUILD_VERSION;
}

iERR ion_version_components(unsigned int *major, unsigned int *minor, unsigned int *patch) {
   if (major != NULL) {
      *major = IONC_VERSION_MAJOR;
   }
   if (major != NULL) {
      *minor = IONC_VERSION_MINOR;
   }
   if (patch != NULL) {
      *patch = IONC_VERSION_PATCH;
   }
   return IERR_OK;
}

char const *ion_version_revision(void) {
   return IONC_VERSION_HASH;
}
